In [1]:
import pandas as pd
from datetime import date, timedelta
pd.set_option('display.max_columns', 500)
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('ufc_scrape/data_fighters2.csv')

In [3]:
df.head()

,name,record,height,weight,reach,stance,dob,event_name,f1_name_a,f1_name_span,f2_name_a,f2_name_span,weightclass,rounds,time,f1_result,f2_result,f1_kd,f2_kd,f1_sig_str,f2_sig_str,f1_sig_str_perc,f2_sig_str_perc,f1_tot_str,f2_tot_str,f1_td,f2_td,f1_td_perc,f2_td_perc,f1_sub_att,f2_sub_att,f1_pass,f2_pass,f1_rev,f2_rev,f1_sig_str_head,f2_sig_str_head,f1_sig_str_body,f2_sig_str_body,f1_sig_str_leg,f2_sig_str_leg,f1_sig_str_dist,f2_sig_str_dist,f1_sig_str_clinch,f2_sig_str_clinch,f1_sig_str_ground,f2_sig_str_ground
0,\n Tom Aaron\n\n,\n Record: 5-3-0\n,\n --\n,\n 155 lbs.\n,\n --\n,\n \n,"\n \n Jul 13, 1978\n \n",\n\n Strikeforce - Heavy Artillery\n\n,Tom Aaron,NaN,NaN,Eric Steenberg,\n \n Catch Weight Bout\n,"\n ,\n 1\n","\n ,\n \n 0:56\n\n",\n W\n,\n L\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\n Hunter Azure\n\n,\n Record: 8-0-0\n,"\n 5' 8""\n",\n 135 lbs.\n,"\n 69""\n",\n Orthodox\n,"\n \n Mar 02, 1992\n \n",\n\n UFC Fight Night: Cowboy vs. Gaethje\n\n,Brad Katona,NaN,Hunter Azure,NaN,\n \n Bantamweight Bout\n,"\n ,\n 3\n","\n ,\n \n 5:00\n\n",\n L\n,\n W\n,0.0,0.0,\n 21 of 60\n,\n 41 of 118\n,\n 35%\n,\n 34%\n,\n 40 of 83\n,\n 55 of 133\n,\n 3 of 12\n,\n 0 of 1\n,\n 25%\n,\n 0%\n,0.0,0.0,1.0,1.0,0.0,1.0,\n 18 of 51\n,\n 25 of 91\n,\n 2 of 7\n,\n 11 of 20\n,\n 1 of 2\n,\n 5 of 7\n,\n 17 of 54\n,\n 33 of 105\n,\n 4 of 6\n,\n 6 of 8\n,\n 0 of 0\n,\n 2 of 5\n
2,\n Michael Byrnes\n\n,\n Record: 5-2-0\n,"\n 5' 11""\n",\n 155 lbs.\n,\n --\n,\n \n,"\n \n Jul 17, 1990\n \n",\n\n Strikeforce - Miami\n\n,NaN,Michael Byrnes,NaN,Dave Zitanick,\n \n Welterweight Bout\n,"\n ,\n 3\n","\n ,\n \n 5:00\n\n",\n W\n,\n L\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,\n Tom Aaron\n\n,\n Record: 5-3-0\n,\n --\n,\n 155 lbs.\n,\n --\n,\n \n,"\n \n Jul 13, 1978\n \n",\n\n Strikeforce - Henderson vs. Babalu\n\n,Tom Aaron,NaN,NaN,Matt Ricehouse,\n \n Lightweight Bout\n,"\n ,\n 3\n","\n ,\n \n 5:00\n\n",\n L\n,\n W\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,\n Ion Cutelaba\n\n,\n Record: 15-5-0 (1 NC)\n ...,"\n 6' 1""\n",\n 205 lbs.\n,"\n 75""\n",\n Southpaw\n,"\n \n Dec 14, 1993\n \n",\n\n UFC Fight Night: MacDonald vs Thompson\n...,Misha Cirkunov,NaN,Ion Cutelaba,NaN,\n \n Light Heavyweight Bout\n,"\n ,\n 3\n","\n ,\n \n 1:22\n\n",\n W\n,\n L\n,0.0,0.0,\n 44 of 94\n,\n 24 of 115\n,\n 46%\n,\n 20%\n,\n 55 of 106\n,\n 25 of 116\n,\n 1 of 3\n,\n 0 of 1\n,\n 33%\n,\n 0%\n,1.0,0.0,1.0,1.0,0.0,0.0,\n 36 of 78\n,\n 12 of 93\n,\n 7 of 15\n,\n 7 of 17\n,\n 1 of 1\n,\n 5 of 5\n,\n 35 of 81\n,\n 20 of 110\n,\n 9 of 13\n,\n 3 of 4\n,\n 0 of 0\n,\n 1 of 1\n

In [4]:
df = df.astype(str)
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
df = df.replace(['nan','--',''], np.nan)
df = df.replace(['\n',',',' Bout',' lbs.'], '', regex=True)

In [5]:
df.head()

,name,record,height,weight,reach,stance,dob,event_name,f1_name_a,f1_name_span,f2_name_a,f2_name_span,weightclass,rounds,time,f1_result,f2_result,f1_kd,f2_kd,f1_sig_str,f2_sig_str,f1_sig_str_perc,f2_sig_str_perc,f1_tot_str,f2_tot_str,f1_td,f2_td,f1_td_perc,f2_td_perc,f1_sub_att,f2_sub_att,f1_pass,f2_pass,f1_rev,f2_rev,f1_sig_str_head,f2_sig_str_head,f1_sig_str_body,f2_sig_str_body,f1_sig_str_leg,f2_sig_str_leg,f1_sig_str_dist,f2_sig_str_dist,f1_sig_str_clinch,f2_sig_str_clinch,f1_sig_str_ground,f2_sig_str_ground
0,Tom Aaron,Record: 5-3-0,NaN,155,NaN,NaN,Jul 13 1978,Strikeforce - Heavy Artillery,Tom Aaron,NaN,NaN,Eric Steenberg,Catch Weight,1,0:56,W,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hunter Azure,Record: 8-0-0,"5' 8""",135,"69""",Orthodox,Mar 02 1992,UFC Fight Night: Cowboy vs. Gaethje,Brad Katona,NaN,Hunter Azure,NaN,Bantamweight,3,5:00,L,W,0.0,0.0,21 of 60,41 of 118,35%,34%,40 of 83,55 of 133,3 of 12,0 of 1,25%,0%,0.0,0.0,1.0,1.0,0.0,1.0,18 of 51,25 of 91,2 of 7,11 of 20,1 of 2,5 of 7,17 of 54,33 of 105,4 of 6,6 of 8,0 of 0,2 of 5
2,Michael Byrnes,Record: 5-2-0,"5' 11""",155,NaN,NaN,Jul 17 1990,Strikeforce - Miami,NaN,Michael Byrnes,NaN,Dave Zitanick,Welterweight,3,5:00,W,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tom Aaron,Record: 5-3-0,NaN,155,NaN,NaN,Jul 13 1978,Strikeforce - Henderson vs. Babalu,Tom Aaron,NaN,NaN,Matt Ricehouse,Lightweight,3,5:00,L,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ion Cutelaba,Record: 15-5-0 (1 NC),"6' 1""",205,"75""",Southpaw,Dec 14 1993,UFC Fight Night: MacDonald vs Thompson,Misha Cirkunov,NaN,Ion Cutelaba,NaN,Light Heavyweight,3,1:22,W,L,0.0,0.0,44 of 94,24 of 115,46%,20%,55 of 106,25 of 116,1 of 3,0 of 1,33%,0%,1.0,0.0,1.0,1.0,0.0,0.0,36 of 78,12 of 93,7 of 15,7 of 17,1 of 1,5 of 5,35 of 81,20 of 110,9 of 13,3 of 4,0 of 0,1 of 1

In [6]:
df['f1_name_a'].fillna(df['f1_name_span'], inplace=True)
df['f2_name_a'].fillna(df['f2_name_span'], inplace=True)
df.rename(columns={'f1_name_a':'f1_name', 'f2_name_a':'f2_name'}, inplace=True)
del df['f1_name_span']
del df['f2_name_span']

In [7]:
df.head(5)

,name,record,height,weight,reach,stance,dob,event_name,f1_name,f2_name,weightclass,rounds,time,f1_result,f2_result,f1_kd,f2_kd,f1_sig_str,f2_sig_str,f1_sig_str_perc,f2_sig_str_perc,f1_tot_str,f2_tot_str,f1_td,f2_td,f1_td_perc,f2_td_perc,f1_sub_att,f2_sub_att,f1_pass,f2_pass,f1_rev,f2_rev,f1_sig_str_head,f2_sig_str_head,f1_sig_str_body,f2_sig_str_body,f1_sig_str_leg,f2_sig_str_leg,f1_sig_str_dist,f2_sig_str_dist,f1_sig_str_clinch,f2_sig_str_clinch,f1_sig_str_ground,f2_sig_str_ground
0,Tom Aaron,Record: 5-3-0,NaN,155,NaN,NaN,Jul 13 1978,Strikeforce - Heavy Artillery,Tom Aaron,Eric Steenberg,Catch Weight,1,0:56,W,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hunter Azure,Record: 8-0-0,"5' 8""",135,"69""",Orthodox,Mar 02 1992,UFC Fight Night: Cowboy vs. Gaethje,Brad Katona,Hunter Azure,Bantamweight,3,5:00,L,W,0.0,0.0,21 of 60,41 of 118,35%,34%,40 of 83,55 of 133,3 of 12,0 of 1,25%,0%,0.0,0.0,1.0,1.0,0.0,1.0,18 of 51,25 of 91,2 of 7,11 of 20,1 of 2,5 of 7,17 of 54,33 of 105,4 of 6,6 of 8,0 of 0,2 of 5
2,Michael Byrnes,Record: 5-2-0,"5' 11""",155,NaN,NaN,Jul 17 1990,Strikeforce - Miami,Michael Byrnes,Dave Zitanick,Welterweight,3,5:00,W,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tom Aaron,Record: 5-3-0,NaN,155,NaN,NaN,Jul 13 1978,Strikeforce - Henderson vs. Babalu,Tom Aaron,Matt Ricehouse,Lightweight,3,5:00,L,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ion Cutelaba,Record: 15-5-0 (1 NC),"6' 1""",205,"75""",Southpaw,Dec 14 1993,UFC Fight Night: MacDonald vs Thompson,Misha Cirkunov,Ion Cutelaba,Light Heavyweight,3,1:22,W,L,0.0,0.0,44 of 94,24 of 115,46%,20%,55 of 106,25 of 116,1 of 3,0 of 1,33%,0%,1.0,0.0,1.0,1.0,0.0,0.0,36 of 78,12 of 93,7 of 15,7 of 17,1 of 1,5 of 5,35 of 81,20 of 110,9 of 13,3 of 4,0 of 0,1 of 1

In [8]:
bout_df = pd.read_csv("ufc_scrape/data_fights.csv")

In [9]:
bout_df.head()

,f1_name,f2_name,f1_str,f2_str,f1_tds,f2_tds,f1_subs,f2_subs,f1_pass,f2_pass,weight_class,method,finisher,round_num,time,event_name,event_date
0,\n Anthony Smith\n,\n Alexander Gustafsson\n ...,49,72,0,1,1,0,1,1,\n Light Heavyweight,\n \n \n\n SUB\n\n,\n Rear Naked Choke\n,4,\n\n \n 2:38\n,\n UFC Fight Night: Gustafsson vs...,"\n ,\n June 01, 2019\n"
1,\n Aleksandar Rakic\n,\n Jimi Manuwa\n,2,2,0,0,0,0,0,0,\n Light Heavyweight,\n \n \n\n KO/TKO\n\n,\n Kick\n,1,\n\n \n 0:47\n,\n UFC Fight Night: Gustafsson vs...,"\n ,\n June 01, 2019\n"
2,\n Makwan Amirkhani\n,\n Chris Fishgold\n,9,16,1,0,1,0,2,0,\n Featherweight,\n \n \n\n SUB\n\n,\n Anaconda Choke\n,2,\n\n \n 4:25\n,\n UFC Fight Night: Gustafsson vs...,"\n ,\n June 01, 2019\n"
3,\n Christos Giagos\n,\n Damir Hadzovic\n,47,24,6,1,0,0,3,0,\n Lightweight,\n \n \n\n U-DEC\n\n,\n \n,3,\n\n \n 5:00\n,\n UFC Fight Night: Gustafsson vs...,"\n ,\n June 01, 2019\n"
4,\n Daniel Teymur\n,\n Sung Bin Jo\n,40,21,1,1,0,1,0,0,\n Featherweight,\n \n \n\n U-DEC\n\n,\n \n,3,\n\n \n 5:00\n,\n UFC Fight Night: Gustafsson vs...,"\n ,\n June 01, 2019\n"

In [10]:
bout_df.duplicated(subset=None).sum()

0

In [11]:
bout_df = bout_df.replace(['\n',','],'', regex=True)

In [12]:
bout_df = bout_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [13]:
bout_df = bout_df[['event_name','event_date']]

In [14]:
bout_df['event_date'] = pd.to_datetime(bout_df['event_date'], format='%B %d %Y')
df['dob'] = pd.to_datetime(df['dob'], format='%b %d %Y', errors='coerce')

In [15]:
bout_df = bout_df.drop_duplicates()

In [16]:
bout_df

                                          event_name event_date
0              UFC Fight Night: Gustafsson vs. Smith 2019-06-01
12                        UFC 238: Cejudo vs. Moraes 2019-06-08
25    UFC Fight Night: Moicano vs. The Korean Zombie 2019-06-22
36           UFC Fight Night: Ngannou vs. Dos Santos 2019-06-29
48                         UFC 239: Jones vs. Santos 2019-07-06
...                                              ...        ...
5475        UFC Fight Night: Anderson vs. Blachowicz 2020-02-15
5488              UFC Fight Night: Felder vs. Hooker 2020-02-22
5500       UFC Fight Night: Benavidez vs. Figueiredo 2020-02-29
5512                    UFC 248: Adesanya vs. Romero 2020-03-07
5523               UFC Fight Night: Lee vs. Oliveira 2020-03-14

[513 rows x 2 columns]

In [17]:
df = pd.merge(df, bout_df, left_on='event_name', right_on='event_name')

In [18]:
df['height'] = df['height'].replace([' ','"'],'', regex=True)
df[['feet','inches']] = df['height'].str.split("'", expand=True)
df['reach'] = df['reach'].replace('"','', regex=True)

In [19]:
df['feet'] = pd.to_numeric(df['feet'])
df['inches'] = pd.to_numeric(df['inches'])
df['reach'] = pd.to_numeric(df['reach'])

df['height'] = round((df['feet']*0.3048) + (df['inches']*0.0254), 2)
df['reach'] = round(df['reach']*0.0254, 2)

df.drop(columns=['feet','inches'], inplace=True)

df['reach'].fillna(df['height'], inplace=True)
df['height'].fillna(df['reach'], inplace=True)

In [20]:
df_full = df.copy()

In [21]:
df.sort_values(by=['name','event_date'], inplace=True)
df.reset_index(drop=True, inplace=True)

In [22]:
f1_mask = (df['name'] == df['f1_name'])
df_valid_f1 = df[f1_mask]

f2_mask = (df['name'] == df['f2_name'])
df_valid_f2 = df[f2_mask]

df['result'] = 0
df.loc[f1_mask, 'result'] = df_valid_f1['f1_result']
df.loc[f2_mask, 'result'] = df_valid_f2['f2_result']

df['kds'] = 0
df.loc[f1_mask, 'kds'] = df_valid_f1['f1_kd']
df.loc[f2_mask, 'kds'] = df_valid_f2['f2_kd']

df['tds'] = 0
df.loc[f1_mask, 'tds'] = df_valid_f1['f1_td']
df.loc[f2_mask, 'tds'] = df_valid_f2['f2_td']

df['sub_att'] = 0
df.loc[f1_mask, 'sub_att'] = df_valid_f1['f1_sub_att']
df.loc[f2_mask, 'sub_att'] = df_valid_f2['f2_sub_att']

df['pass'] = 0
df.loc[f1_mask, 'pass'] = df_valid_f1['f1_pass']
df.loc[f2_mask, 'pass'] = df_valid_f2['f2_pass']

df['rev'] = 0
df.loc[f1_mask, 'rev'] = df_valid_f1['f1_rev']
df.loc[f2_mask, 'rev'] = df_valid_f2['f2_rev']

df['tot_str'] = 0
df.loc[f1_mask, 'tot_str'] = df_valid_f1['f1_tot_str']
df.loc[f2_mask, 'tot_str'] = df_valid_f2['f2_tot_str']

df['sig_str_head'] = 0
df.loc[f1_mask, 'sig_str_head'] = df_valid_f1['f1_sig_str_head']
df.loc[f2_mask, 'sig_str_head'] = df_valid_f2['f2_sig_str_head']

df['sig_str_body'] = 0
df.loc[f1_mask, 'sig_str_body'] = df_valid_f1['f1_sig_str_body']
df.loc[f2_mask, 'sig_str_body'] = df_valid_f2['f2_sig_str_body']

df['sig_str_leg'] = 0
df.loc[f1_mask, 'sig_str_leg'] = df_valid_f1['f1_sig_str_leg']
df.loc[f2_mask, 'sig_str_leg'] = df_valid_f2['f2_sig_str_leg']

df['sig_str_dist'] = 0
df.loc[f1_mask, 'sig_str_dist'] = df_valid_f1['f1_sig_str_dist']
df.loc[f2_mask, 'sig_str_dist'] = df_valid_f2['f2_sig_str_dist']

df['sig_str_clinch'] = 0
df.loc[f1_mask, 'sig_str_clinch'] = df_valid_f1['f1_sig_str_clinch']
df.loc[f2_mask, 'sig_str_clinch'] = df_valid_f2['f2_sig_str_clinch']

df['sig_str_ground'] = 0
df.loc[f1_mask, 'sig_str_ground'] = df_valid_f1['f1_sig_str_ground']
df.loc[f2_mask, 'sig_str_ground'] = df_valid_f2['f2_sig_str_ground']

In [23]:
df = df.drop(columns=['f1_result','f2_result',
                     'f1_kd','f2_kd',
                     'f1_td','f2_td',
                     'f1_sub_att','f2_sub_att',
                     'f1_rev','f2_rev',
                     'f1_sig_str_head','f2_sig_str_head',
                     'f1_sig_str_body','f2_sig_str_body',
                     'f1_sig_str_leg','f2_sig_str_leg',
                     'f1_sig_str_dist','f2_sig_str_dist',
                     'f1_sig_str_clinch','f2_sig_str_clinch',
                     'f1_sig_str_ground','f2_sig_str_ground',
                     'f1_sig_str','f2_sig_str',
                     'f1_sig_str_perc','f2_sig_str_perc',
                     'f1_tot_str','f2_tot_str',
                     'f1_td_perc','f2_td_perc',
                     'f1_pass','f2_pass'])

In [24]:
df.replace(' of ',' ', regex=True, inplace=True)

df[['tds_succ','tds_att']] = df['tds'].str.split(" ", expand=True)
df.drop(columns=['tds'], inplace=True)

df[['tot_str_succ','tot_str_att']] = df['tot_str'].str.split(" ", expand=True)
df.drop(columns=['tot_str'], inplace=True)

df[['sig_str_head_succ','sig_str_head_att']] = df['sig_str_head'].str.split(" ", expand=True)
df.drop(columns=['sig_str_head'], inplace=True)

df[['sig_str_body_succ','sig_str_body_att']] = df['sig_str_body'].str.split(" ", expand=True)
df.drop(columns=['sig_str_body'], inplace=True)

df[['sig_str_leg_succ','sig_str_leg_att']] = df['sig_str_leg'].str.split(" ", expand=True)
df.drop(columns=['sig_str_leg'], inplace=True)

df[['sig_str_dist_succ','sig_str_dist_att']] = df['sig_str_dist'].str.split(" ", expand=True)
df.drop(columns=['sig_str_dist'], inplace=True)

df[['sig_str_clinch_succ','sig_str_clinch_att']] = df['sig_str_clinch'].str.split(" ", expand=True)
df.drop(columns=['sig_str_clinch'], inplace=True)

df[['sig_str_ground_succ','sig_str_ground_att']] = df['sig_str_ground'].str.split(" ", expand=True)
df.drop(columns=['sig_str_ground'], inplace=True)

In [25]:
df.head()

,name,record,height,weight,reach,stance,dob,event_name,f1_name,f2_name,weightclass,rounds,time,event_date,result,kds,sub_att,pass,rev,tds_succ,tds_att,tot_str_succ,tot_str_att,sig_str_head_succ,sig_str_head_att,sig_str_body_succ,sig_str_body_att,sig_str_leg_succ,sig_str_leg_att,sig_str_dist_succ,sig_str_dist_att,sig_str_clinch_succ,sig_str_clinch_att,sig_str_ground_succ,sig_str_ground_att
0,Aalon Cruz,Record: 8-3-0,1.83,145,1.98,Switch,1989-09-20,UFC Fight Night: Benavidez vs. Figueiredo,Aalon Cruz,Spike Carlyle,Featherweight,1,1:25,2020-02-29,L,0.0,0.0,0.0,0.0,0,1,2,12,2,4,0,4,0,4,2,12,0,0,0,0
1,Aaron Brink,Record: 25-21-0 (1 NC),1.91,205,1.91,Orthodox,1974-11-12,UFC 28: High Stakes,Andrei Arlovski,Aaron Brink,Heavyweight,1,0:55,2000-11-17,L,0.0,0.0,0.0,0.0,0,1,0,5,0,5,0,0,0,0,0,3,0,2,0,0
2,Aaron Phillips,Record: 8-2-0,1.75,135,1.78,Southpaw,1989-08-05,UFC 173: Barao vs Dillashaw,Sam Sicilia,Aaron Phillips,Featherweight,3,5:00,2014-05-24,L,0.0,1.0,1.0,1.0,0,0,109,137,5,23,12,14,1,3,9,26,3,6,6,8
3,Aaron Phillips,Record: 8-2-0,1.75,135,1.78,Southpaw,1989-08-05,UFC Fight Night: Henderson vs Dos Anjos,Aaron Phillips,Matt Hobar,Bantamweight,3,5:00,2014-08-23,L,0.0,0.0,0.0,0.0,0,1,230,279,23,39,12,12,3,3,14,25,17,18,7,11
4,Aaron Riley,Record: 29-14-1,1.73,155,1.75,Southpaw,1980-12-09,UFC 37: High Impact,Robbie Lawler,Aaron Riley,Welterweight,3,5:00,2002-05-10,L,0.0,1.0,1.0,0.0,0,3,93,170,18,83,18,20,19,27,31,83,24,47,0,0

In [26]:
df.isnull().sum()

name                      0
record                    0
height                   24
weight                   22
reach                    24
stance                  272
dob                     273
event_name                0
f1_name                   0
f2_name                   0
weightclass            2876
rounds                    0
time                      0
event_date                0
result                    0
kds                      52
sub_att                  52
pass                     52
rev                      52
tds_succ                 52
tds_att                  52
tot_str_succ             52
tot_str_att              52
sig_str_head_succ        52
sig_str_head_att         52
sig_str_body_succ        52
sig_str_body_att         52
sig_str_leg_succ         52
sig_str_leg_att          52
sig_str_dist_succ        52
sig_str_dist_att         52
sig_str_clinch_succ      52
sig_str_clinch_att       52
sig_str_ground_succ      52
sig_str_ground_att       52
dtype: int64

In [27]:
df[['minutes', 'seconds']] = df['time'].str.split(':', expand=True)
df[['minutes', 'seconds', 'rounds']] = df[['minutes', 'seconds', 'rounds']].astype(float)

In [28]:
df['fight_time'] = round(((df['rounds'] - 1) * 5) + df['minutes'] + (df['seconds']/60), 2)

In [29]:
columns = ['kds','sub_att','pass','rev','tds_succ','tds_att','tot_str_succ','tot_str_att',
           'sig_str_head_succ','sig_str_head_att','sig_str_body_succ','sig_str_body_att',
           'sig_str_leg_succ','sig_str_leg_att','sig_str_dist_succ','sig_str_dist_att',
           'sig_str_clinch_succ','sig_str_clinch_att','sig_str_ground_succ','sig_str_ground_att','fight_time']

new_columns = ['kds_sum','sub_att_sum','pass_sum','rev_sum','tds_succ_sum','tds_att_sum','tot_str_succ_sum','tot_str_att_sum',
               'sig_str_head_succ_sum','sig_str_head_att_sum','sig_str_body_succ_sum','sig_str_body_att_sum',
               'sig_str_leg_succ_sum','sig_str_leg_att_sum','sig_str_dist_succ_sum','sig_str_dist_att_sum',
               'sig_str_clinch_succ_sum','sig_str_clinch_att_sum','sig_str_ground_succ_sum','sig_str_ground_att_sum','fight_time_sum']

df[columns] = df[columns].astype(float)

In [33]:
df[new_columns] = df.groupby('name')[columns].rolling(1).sum()

TypeError: incompatible index of inserted column with frame index

In [ ]:
df.isnull().sum()

In [ ]:
df[new_columns] = df[new_columns].fillna(0)
df[columns] = df[columns].fillna(0)

In [ ]:
df['kds_sum'] = df['kds_sum'] - df['kds']
df['sub_att_sum'] = df['sub_att_sum'] - df['sub_att']
df['pass_sum'] = df['pass_sum'] - df['pass']
df['rev_sum'] = df['rev_sum'] - df['rev']
df['tds_succ_sum'] = df['tds_succ_sum'] - df['tds_succ']
df['tds_att_sum'] = df['tds_att_sum'] - df['tds_att']
df['tot_str_succ_sum'] = df['tot_str_succ_sum'] - df['tot_str_succ']
df['tot_str_att_sum'] = df['tot_str_att_sum'] - df['tot_str_att']
df['sig_str_head_succ_sum'] = df['sig_str_head_succ_sum'] - df['sig_str_head_succ']
df['sig_str_head_att_sum'] = df['sig_str_head_att_sum'] - df['sig_str_head_att']
df['sig_str_body_succ_sum'] = df['sig_str_body_succ_sum'] - df['sig_str_body_succ']
df['sig_str_body_att_sum'] = df['sig_str_body_att_sum'] - df['sig_str_body_att']
df['sig_str_leg_succ_sum'] = df['sig_str_leg_succ_sum'] - df['sig_str_leg_succ']
df['sig_str_leg_att_sum'] = df['sig_str_leg_att_sum'] - df['sig_str_leg_att']
df['sig_str_dist_succ_sum'] = df['sig_str_dist_succ_sum'] - df['sig_str_dist_succ']
df['sig_str_dist_att_sum'] = df['sig_str_dist_att_sum'] - df['sig_str_dist_att']
df['sig_str_clinch_succ_sum'] = df['sig_str_clinch_succ_sum'] - df['sig_str_clinch_succ']
df['sig_str_clinch_att_sum'] = df['sig_str_clinch_att_sum'] - df['sig_str_clinch_att']
df['sig_str_ground_succ_sum'] = df['sig_str_ground_succ_sum'] - df['sig_str_ground_succ']
df['sig_str_ground_att_sum'] = df['sig_str_ground_att_sum'] - df['sig_str_ground_att']
df['fight_time_sum'] = df['fight_time_sum'] - df['fight_time']

In [ ]:
df.isnull().sum()

In [ ]:
df['kds_per_min'] = round(df['kds_sum']/df['fight_time_sum'], 2)
df['sub_att_per_min'] = round(df['sub_att_sum']/df['fight_time_sum'], 2)
df['pass_per_min'] = round(df['pass_sum']/df['fight_time_sum'], 2)
df['rev_per_min'] = round(df['rev_sum']/df['fight_time_sum'], 2)

In [ ]:
df['tds_acc'] = round(df['tds_succ_sum']/df['tds_att_sum'], 2)
df['tds_succ_per_min'] = round(df['tds_succ_sum']/df['fight_time_sum'], 2)
df['tds_att_per_min'] = round(df['tds_att_sum']/df['fight_time_sum'], 2)

df['tot_str_acc'] = round(df['tot_str_succ_sum']/df['tot_str_att_sum'], 2)
df['tot_str_succ_per_min'] = round(df['tot_str_succ_sum']/df['fight_time_sum'], 2)
df['tot_str_att_per_min'] = round(df['tot_str_att_sum']/df['fight_time_sum'], 2)

df['sig_str_head_acc'] = round(df['sig_str_head_succ_sum']/df['sig_str_head_att_sum'], 2)
df['sig_str_head_succ_per_min'] = round(df['sig_str_head_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_head_att_per_min'] = round(df['sig_str_head_att_sum']/df['fight_time_sum'], 2)

df['sig_str_body_acc'] = round(df['sig_str_body_succ_sum']/df['sig_str_body_att_sum'], 2)
df['sig_str_body_succ_per_min'] = round(df['sig_str_body_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_body_att_per_min'] = round(df['sig_str_body_att_sum']/df['fight_time_sum'], 2)

df['sig_str_leg_acc'] = round(df['sig_str_leg_succ_sum']/df['sig_str_leg_att_sum'], 2)
df['sig_str_leg_succ_per_min'] = round(df['sig_str_leg_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_leg_att_per_min'] = round(df['sig_str_leg_att_sum']/df['fight_time_sum'], 2)

df['sig_str_dist_acc'] = round(df['sig_str_dist_succ_sum']/df['sig_str_dist_att_sum'], 2)
df['sig_str_dist_succ_per_min'] = round(df['sig_str_dist_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_dist_att_per_min'] = round(df['sig_str_dist_att_sum']/df['fight_time_sum'], 2)

df['sig_str_clinch_acc'] = round(df['sig_str_clinch_succ_sum']/df['sig_str_clinch_att_sum'], 2)
df['sig_str_clinch_succ_per_min'] = round(df['sig_str_clinch_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_clinch_att_per_min'] = round(df['sig_str_clinch_att_sum']/df['fight_time_sum'], 2)

df['sig_str_ground_acc'] = round(df['sig_str_ground_succ_sum']/df['sig_str_ground_att_sum'], 2)
df['sig_str_ground_succ_per_min'] = round(df['sig_str_ground_succ_sum']/df['fight_time_sum'], 2)
df['sig_str_ground_att_per_min'] = round(df['sig_str_ground_att_sum']/df['fight_time_sum'], 2)

In [ ]:
df.tail()

In [ ]:
# new_columns_to_drop = ['kds_sum','sub_att_sum','pass_sum','rev_sum','tds_succ_sum','tds_att_sum','tot_str_succ_sum','tot_str_att_sum',
#                'sig_str_head_succ_sum','sig_str_head_att_sum','sig_str_body_succ_sum','sig_str_body_att_sum',
#                'sig_str_leg_succ_sum','sig_str_leg_att_sum','sig_str_dist_succ_sum','sig_str_dist_att_sum',
#                'sig_str_clinch_succ_sum','sig_str_clinch_att_sum','sig_str_ground_succ_sum','sig_str_ground_att_sum']

In [ ]:
df.drop(columns=columns, inplace=True)
# df.drop(columns=new_columns_to_drop, inplace=True)

In [ ]:
df['age'] = df['event_date'] - df['dob']
df['age'] = round(df['age']/np.timedelta64(1,'Y'), 2)

In [ ]:
df.tail()

In [ ]:
df[df['weightclass'].isnull()]

In [ ]:
df['weight'] = df['weight'].astype(float)

In [ ]:
for i, row in df.iterrows():
    if pd.isnull(row['weightclass']) and (row['weight'] <= 115):
        df.loc[i, 'weightclass'] = 'Strawweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 115) and (row['weight'] <= 125):
        df.loc[i, 'weightclass'] = 'Flyweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 125) and (row['weight'] <= 135):
        df.loc[i, 'weightclass'] = 'Bantamweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 135) and (row['weight'] <= 145):
        df.loc[i, 'weightclass'] = 'Featherweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 145) and (row['weight'] <= 155):
        df.loc[i, 'weightclass'] = 'Lightweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 155) and (row['weight'] <= 170):
        df.loc[i, 'weightclass'] = 'Welterweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 170) and (row['weight'] <= 185):
        df.loc[i, 'weightclass'] = 'Middleweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 185) and (row['weight'] <= 205):
        df.loc[i, 'weightclass'] = 'Middleweight'
    if pd.isnull(row['weightclass']) and (row['weight'] > 205):
        df.loc[i, 'weightclass'] = 'Heavyweight'
    else:
        pass

In [ ]:
df['weightclass'] = df['weightclass'].replace("Women's ", '', regex=True)

In [ ]:
df.isnull().sum()

In [ ]:
stats_columns = ['kds_per_min','sub_att_per_min','pass_per_min','rev_per_min','tds_acc','tds_succ_per_min',
                'tds_att_per_min','tot_str_acc','tot_str_succ_per_min','tot_str_att_per_min',
                'sig_str_head_acc','sig_str_head_succ_per_min','sig_str_head_att_per_min','sig_str_body_acc',
                'sig_str_body_succ_per_min','sig_str_body_att_per_min','sig_str_leg_acc','sig_str_leg_succ_per_min',
                'sig_str_leg_att_per_min','sig_str_dist_acc','sig_str_dist_succ_per_min','sig_str_dist_att_per_min',
                'sig_str_clinch_acc','sig_str_clinch_succ_per_min','sig_str_clinch_att_per_min','sig_str_ground_acc',
                'sig_str_ground_succ_per_min','sig_str_ground_att_per_min']

In [ ]:
df[stats_columns] = df[stats_columns].fillna(0)

In [ ]:
df['record'] = df['record'].str.replace('Record: ','', regex=True)

In [ ]:
df[['wins','losses','draws']] = df['record'].str.split('-', expand=True)
df['draws'] = df['draws'].str.split(' ').str[0]
df.drop(columns=['record'], inplace=True)

In [ ]:
df.head()

In [ ]:
df_result = df[['name','event_date','result','wins','losses','draws']]
df_result.rename(columns={'wins':'record_wins','losses':'record_losses','draws':'record_draws'}, inplace=True)

In [ ]:
df_result['win'] = df_result['result'].apply(lambda x: 1 if (x == 'W') else 0)
df_result['loss'] = df_result['result'].apply(lambda x: 1 if (x == 'L') else 0)
df_result['draw'] = df_result['result'].apply(lambda x: 1 if (x == 'D') else 0)

In [ ]:
df_result

In [ ]:
result_new_cols = ['win_sum','loss_sum','draw_sum']
result_cols = ['win','loss','draw']
df_result[result_new_cols] = df_result.groupby('name')[result_cols].cumsum()

In [ ]:
df_result

In [ ]:
ufc_wins = df_result['win_sum'] - df_result['win']
ufc_losses = df_result['loss_sum'] - df_result['loss']
ufc_draws = df_result['draw_sum'] - df_result['draw']

In [ ]:
df_result = df_result.sort_values(by=['name','event_date'], ascending=[True, False])

In [ ]:
df_result

In [ ]:
df_result = df_result[['win_sum','loss_sum','draw_sum']]

In [ ]:
df_result.reset_index(drop=True, inplace=True)

In [ ]:
df_result

In [ ]:
df = df.merge(df_result, left_index=True, right_index=True)

In [ ]:
df.head()

In [ ]:
df['ufc_wins'] = ufc_wins
df['ufc_losses'] = ufc_losses
df['ufc_draws'] = ufc_draws

In [ ]:
df[['wins','losses','draws']] = df[['wins','losses','draws']].astype(float)

In [ ]:
df['wins'] = df['wins'] - df['win_sum']
df['losses'] = df['losses'] - df['loss_sum']
df['draws'] = df['draws'] - df['draw_sum']

In [ ]:
df.drop(columns=['win_sum','loss_sum','draw_sum'], inplace=True)

In [ ]:
df_age = df.dropna(subset=['age'], axis=0)

In [ ]:
df_age = df_age.groupby('name').first().reset_index()

In [ ]:
first_fight_age = int(round(df['age'].mean()))
first_fight_age

In [ ]:
df_age2 = df.copy()

In [ ]:
df_age2 = df_age2.groupby('name').first().reset_index()

In [ ]:
df_age2[df_age2['dob'].isnull()]

In [ ]:
df_age2['age'] = df_age2['age'].fillna(first_fight_age)

In [ ]:
df_age2['dob'] = df_age2['dob'].fillna(df['event_date'] - timedelta(days=(365*first_fight_age)))

In [ ]:
df_age2 = df_age2[['name','dob']]
df_age2.rename(columns={'dob':'dob_filled'}, inplace=True)

In [ ]:
df = df.merge(df_age2, left_on='name', right_on='name')
df.drop(columns=['dob'], inplace=True)

In [ ]:
df['age'] = df['event_date'] - df['dob_filled']
df['age'] = round(df['age']/np.timedelta64(1,'Y'), 2)
df.rename(columns={'dob_filled':'dob'}, inplace=True)

In [ ]:
df[df['name'] == 'Alex Hunter']

In [ ]:
df['stance'].value_counts(normalize=True)

In [ ]:
df['stance'].fillna('Orthodox', inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df_null = df[df['height'].isnull()]

In [ ]:
len(df_null)

In [ ]:
df_null.head()

In [ ]:
df['height'] = df.groupby('weightclass')['height'].apply(lambda x: x.fillna(x.median()))
df['weight'] = df.groupby('weightclass')['weight'].apply(lambda x: x.fillna(x.median()))
df['reach'] = df.groupby('weightclass')['reach'].apply(lambda x: x.fillna(x.median()))

In [ ]:
df = pd.get_dummies(df, columns=['weightclass','stance'])

In [ ]:
df.drop(columns=['rounds','time','minutes','seconds'], inplace=True)

In [ ]:
df_copy = df.copy()

In [ ]:
df2 = df.merge(df_copy, how='outer', left_on=['f1_name','f2_name','event_name'], right_on=['f1_name','f2_name','event_name'])

In [ ]:
df2 = df2[df2['name_x'] != df2['name_y']]

In [ ]:
len(df2)

In [ ]:
df2.head()

In [ ]:
df2.drop(columns=['f1_name','f2_name'], inplace=True)

In [ ]:
df2 = df2.iloc[::2]

In [ ]:
df2['result_x'].value_counts(normalize=True)

In [ ]:
len(df2)

In [ ]:
df2

In [ ]:
df2 = df2[df2['result_x'] != 'NC']
df2 = df2[df2['result_x'] != 'D']

In [ ]:
df2['result_y'].value_counts(normalize=True)

In [ ]:
df2 = pd.get_dummies(df2, columns=['result_x'])

In [ ]:
df2.rename(columns={'result_x_L':'fy_win','result_x_W':'fx_win'}, inplace=True)

In [ ]:
df2.drop(columns=['fy_win'], inplace=True)

In [ ]:
df2.head()

In [ ]:
df2.reset_index(drop=True, inplace=True)

In [ ]:
# df_bool = pd.DataFrame(df2['weightclass_x'] == df2['weightclass_y'])

In [ ]:
# df_bool[0].value_counts()

In [ ]:
df2 = df2[df2['fight_time_sum_x'] != 0]
df2 = df2[df2['fight_time_sum_y'] != 0]

In [ ]:
df2.reset_index(drop=True, inplace=True)

In [ ]:
df2.drop(columns=['name_x','name_y','event_name','event_date_x','event_date_y','dob_x','dob_y','result_y','wins_x','losses_x','draws_x','wins_y','losses_y','draws_y'], inplace=True)

In [ ]:
df2.to_csv('data_cleaned2.csv', index=False)

In [34]:
dummy_df = pd.DataFrame()
a = ['x','x','x','x','x','x','y','y','z','z','z','z']
b = [1,2,3,1,2,3,4,4,5,2,1,1]
dummy_df['a'] = a
dummy_df['b'] = b

In [35]:
dummy_df

    a  b
0   x  1
1   x  2
2   x  3
3   x  1
4   x  2
5   x  3
6   y  4
7   y  4
8   z  5
9   z  2
10  z  1
11  z  1